
import java.awt.Dimension;
import java.awt.Image;
import java.awt.PopupMenu;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.imageio.ImageIO;
import static javax.imageio.ImageIO.read;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MSI GF63
 */
public class ktp extends javax.swing.JFrame {

    private Object ImageIO;

    /**
     * Creates new form ktp
     */
    public ktp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtprovinsi = new javax.swing.JTextField();
        txtkabupaten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttempat = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtrtrw = new javax.swing.JTextField();
        txtkelurahan = new javax.swing.JTextField();
        txtkecamatan = new javax.swing.JTextField();
        txtpekerjaan = new javax.swing.JTextField();
        txtberlakuhingga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmbagama = new javax.swing.JComboBox<>();
        cmbstatusperkawinan = new javax.swing.JComboBox<>();
        cmbgolongandarah = new javax.swing.JComboBox<>();
        cblakilaki = new javax.swing.JCheckBox();
        cbperempuan = new javax.swing.JCheckBox();
        cmbkewarganegaraan = new javax.swing.JComboBox<>();
        lbgambar = new javax.swing.JLabel();
        btupload = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbnama = new javax.swing.JLabel();
        lbtempat = new javax.swing.JLabel();
        lbjeniskelamin = new javax.swing.JLabel();
        lbalamat = new javax.swing.JLabel();
        lbrtrw = new javax.swing.JLabel();
        lbkelurahan = new javax.swing.JLabel();
        lbkecamatan = new javax.swing.JLabel();
        lbagama = new javax.swing.JLabel();
        lbstatusperkawinan = new javax.swing.JLabel();
        lbpekerjaan = new javax.swing.JLabel();
        lbnik = new javax.swing.JLabel();
        lbkewarganegaraan = new javax.swing.JLabel();
        lbberlakuhingga = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbprovinsi = new javax.swing.JLabel();
        lbkabupaten = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbgolongandarah = new javax.swing.JLabel();
        bthapus = new javax.swing.JButton();
        lbgambar1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("KABUPATEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 35, 81, -1));

        jLabel2.setText("PROVINSI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 7, 61, -1));

        txtprovinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprovinsiActionPerformed(evt);
            }
        });
        getContentPane().add(txtprovinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 4, 71, -1));

        txtkabupaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkabupatenActionPerformed(evt);
            }
        });
        getContentPane().add(txtkabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 32, 71, -1));

        jLabel3.setText("NIK                                  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 90, -1, -1));

        jLabel4.setText("Nama                              :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 124, -1, -1));

        jLabel5.setText("Tempat/Tgl Lahir           :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 152, 130, -1));

        jLabel6.setText("Jenis Kelamin                 :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 185, 130, -1));

        jLabel7.setText("Alamat                           :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 218, 130, -1));

        jLabel8.setText("RT/RW                    :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 246, -1, -1));

        jLabel9.setText("Kel/Desa                :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 280, -1, -1));

        jLabel10.setText("Kecamatan            :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 308, 102, -1));

        jLabel11.setText("Agama                         :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 339, 125, -1));

        jLabel12.setText("Status Perkawinan       :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 370, 130, -1));

        jLabel13.setText("Pekerjaan                    :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 410, 130, -1));

        jLabel14.setText("Kewarganegaraan      :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 438, 130, -1));

        jLabel15.setText("Berlaku Hingga          :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 463, 130, -1));

        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });
        getContentPane().add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 87, 140, -1));

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 121, 140, -1));

        txttempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempatActionPerformed(evt);
            }
        });
        getContentPane().add(txttempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 149, 140, -1));

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 215, 140, -1));

        txtrtrw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrtrwActionPerformed(evt);
            }
        });
        getContentPane().add(txtrtrw, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 243, 140, -1));

        txtkelurahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkelurahanActionPerformed(evt);
            }
        });
        getContentPane().add(txtkelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 277, 140, -1));

        txtkecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkecamatanActionPerformed(evt);
            }
        });
        getContentPane().add(txtkecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 308, 140, -1));

        txtpekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpekerjaanActionPerformed(evt);
            }
        });
        getContentPane().add(txtpekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 407, 140, -1));

        txtberlakuhingga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberlakuhinggaActionPerformed(evt);
            }
        });
        getContentPane().add(txtberlakuhingga, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 463, 140, -1));

        jLabel16.setText("Gol. Darah          :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 152, -1, -1));

        cmbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristwn", "Katholik", "Budha", "Konghucu" }));
        getContentPane().add(cmbagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 336, 140, -1));

        cmbstatusperkawinan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Kawin", "Kawin", "Cerai" }));
        cmbstatusperkawinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbstatusperkawinanActionPerformed(evt);
            }
        });
        getContentPane().add(cmbstatusperkawinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 367, 140, -1));

        cmbgolongandarah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        cmbgolongandarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgolongandarahActionPerformed(evt);
            }
        });
        getContentPane().add(cmbgolongandarah, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 149, -1, -1));

        cblakilaki.setText("Laki-Laki");
        cblakilaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblakilakiActionPerformed(evt);
            }
        });
        getContentPane().add(cblakilaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 183, 85, -1));

        cbperempuan.setText("Perempuan");
        cbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbperempuanActionPerformed(evt);
            }
        });
        getContentPane().add(cbperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 183, 85, -1));

        cmbkewarganegaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WNI", "WNA" }));
        cmbkewarganegaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkewarganegaraanActionPerformed(evt);
            }
        });
        getContentPane().add(cmbkewarganegaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 435, 140, -1));

        lbgambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbgambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 258, 80, 100));

        btupload.setText("Upload");
        btupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btuploadActionPerformed(evt);
            }
        });
        getContentPane().add(btupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 385, -1, -1));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Nama                              :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Tempat/Tgl Lahir          :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 140, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Jenis Kelamin              :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 130, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Alamat                           :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 130, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("RT/RW                    :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Kel/Desa                :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Kecamatan            :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 102, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("Agama                         :");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 125, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("Status Perkawinan       :");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 130, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("Pekerjaan                    :");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 130, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("NIK                                  :");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Kewarganegaraan      :");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 130, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("Berlaku Hingga          :");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 130, -1));

        lbnama.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbnama.setText(" ");
        getContentPane().add(lbnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 136, -1));

        lbtempat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbtempat.setText(" ");
        getContentPane().add(lbtempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 136, -1));

        lbjeniskelamin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbjeniskelamin.setText(" ");
        getContentPane().add(lbjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 136, -1));

        lbalamat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbalamat.setText("  ");
        getContentPane().add(lbalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 136, -1));

        lbrtrw.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbrtrw.setText(" ");
        getContentPane().add(lbrtrw, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 136, -1));

        lbkelurahan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbkelurahan.setText(" ");
        getContentPane().add(lbkelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 136, -1));

        lbkecamatan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbkecamatan.setText(" ");
        getContentPane().add(lbkecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 136, -1));

        lbagama.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbagama.setText(" ");
        getContentPane().add(lbagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 136, -1));

        lbstatusperkawinan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbstatusperkawinan.setText(" ");
        getContentPane().add(lbstatusperkawinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 136, -1));

        lbpekerjaan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbpekerjaan.setText(" ");
        getContentPane().add(lbpekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 136, -1));

        lbnik.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbnik.setText(" ");
        getContentPane().add(lbnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 136, -1));

        lbkewarganegaraan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbkewarganegaraan.setText(" ");
        getContentPane().add(lbkewarganegaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 136, -1));

        lbberlakuhingga.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbberlakuhingga.setText(" ");
        getContentPane().add(lbberlakuhingga, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 136, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setText("KABUPATEN");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 81, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("PROVINSI");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 61, -1));

        lbprovinsi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbprovinsi.setText(" ");
        getContentPane().add(lbprovinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 130, -1));

        lbkabupaten.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbkabupaten.setText(" ");
        getContentPane().add(lbkabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 130, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel32.setText("Gol. Darah          :");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, -1, -1));

        lbgolongandarah.setText(" ");
        getContentPane().add(lbgolongandarah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 59, -1));

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 530, -1, -1));

        lbgambar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbgambar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbgambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, 80, 100));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel33.setText("jLabel33");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 510, 470));

        jLabel34.setBackground(new java.awt.Color(153, 204, 255));
        jLabel34.setText(" ");
        jLabel34.setOpaque(true);
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1180, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprovinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprovinsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprovinsiActionPerformed

    private void txtkabupatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkabupatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkabupatenActionPerformed

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txttempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempatActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void txtrtrwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrtrwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrtrwActionPerformed

    private void txtkelurahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkelurahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkelurahanActionPerformed

    private void txtkecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkecamatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkecamatanActionPerformed

    private void cmbstatusperkawinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbstatusperkawinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbstatusperkawinanActionPerformed

    private void txtpekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpekerjaanActionPerformed

    private void cmbkewarganegaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkewarganegaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkewarganegaraanActionPerformed

    private void txtberlakuhinggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberlakuhinggaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberlakuhinggaActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        String agm,sts,warga,darah;
        String jeniskelamin="";
        if(cblakilaki.isSelected()){
            jeniskelamin="Laki-Laki";
        }
        if(cbperempuan.isSelected()){
            jeniskelamin="Perempuan";
        }
        
        agm=cmbagama.getSelectedItem().toString();
        sts=cmbstatusperkawinan.getSelectedItem().toString();
        warga=cmbkewarganegaraan.getSelectedItem().toString();
        darah=cmbgolongandarah.getSelectedItem().toString();
        
        lbprovinsi.setText(txtprovinsi.getText());
        lbkabupaten.setText(txtkabupaten.getText());
        lbnik.setText(txtnik.getText());
        lbnama.setText(txtnama.getText());
        lbtempat.setText(txttempat.getText());
        lbjeniskelamin.setText(jeniskelamin);
        lbalamat.setText(txtalamat.getText());
        lbrtrw.setText(txtrtrw.getText());
        lbkelurahan.setText(txtkelurahan.getText());
        lbkecamatan.setText(txtkecamatan.getText());
        lbagama.setText(agm);
        lbstatusperkawinan.setText(sts);
        lbpekerjaan.setText(txtpekerjaan.getText());
        lbkewarganegaraan.setText(warga);
        lbberlakuhingga.setText(txtberlakuhingga.getText());
        lbgolongandarah.setText(darah);
        lbgambar1.setIcon(lbgambar.getIcon());
        
        
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btuploadActionPerformed
       JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select an Image");

    // Set the file filter for images
    fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
        public boolean accept(File f) {
            if (f.isDirectory()) {
                return true;
            } else {
                String filename = f.getName().toLowerCase();
                return filename.endsWith(".jpg") || filename.endsWith(".jpeg") || filename.endsWith(".png") || filename.endsWith(".gif");
            }
        }

        public String getDescription() {
            return "Image Files (*.jpg, *.jpeg, *.png, *.gif)";
        }
    });
    int result = fileChooser.showOpenDialog(this);

    // If an image file is selected, display it
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        BufferedImage img = null;
             try {
                 img = read(selectedFile);
             } catch (IOException ex) {
                 Logger.getLogger(KTP.class.getName()).log(Level.SEVERE, null, ex);
             }
        Image scaledImage = img.getScaledInstance(80, 100, Image.SCALE_SMOOTH); // Scale the image
        ImageIcon imageIcon = new ImageIcon(scaledImage);
        lbgambar.setIcon(imageIcon);
    }



    }//GEN-LAST:event_btuploadActionPerformed

    private void cmbgolongandarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgolongandarahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgolongandarahActionPerformed

    private void cblakilakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblakilakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cblakilakiActionPerformed

    private void cbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbperempuanActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
      lbprovinsi.setText("");
      lbkabupaten.setText("");
        lbnik.setText("");
       lbnama.setText("");
       lbtempat.setText("");
       lbjeniskelamin.setText("");
       lbalamat.setText("");
       lbrtrw.setText("");
       lbkelurahan.setText("");
       lbkelurahan.setText("");
       lbkecamatan.setText("");
       lbagama.setText("");
       lbstatusperkawinan.setText("");
       lbpekerjaan.setText("");
       lbkewarganegaraan.setText("");
       lbberlakuhingga.setText("");
       lbgolongandarah.setText("");
       lbgambar1.setIcon(null);
    }//GEN-LAST:event_bthapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ktp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btupload;
    private javax.swing.JCheckBox cblakilaki;
    private javax.swing.JCheckBox cbperempuan;
    private javax.swing.JComboBox<String> cmbagama;
    private javax.swing.JComboBox<String> cmbgolongandarah;
    private javax.swing.JComboBox<String> cmbkewarganegaraan;
    private javax.swing.JComboBox<String> cmbstatusperkawinan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbagama;
    private javax.swing.JLabel lbalamat;
    private javax.swing.JLabel lbberlakuhingga;
    private javax.swing.JLabel lbgambar;
    private javax.swing.JLabel lbgambar1;
    private javax.swing.JLabel lbgolongandarah;
    private javax.swing.JLabel lbjeniskelamin;
    private javax.swing.JLabel lbkabupaten;
    private javax.swing.JLabel lbkecamatan;
    private javax.swing.JLabel lbkelurahan;
    private javax.swing.JLabel lbkewarganegaraan;
    private javax.swing.JLabel lbnama;
    private javax.swing.JLabel lbnik;
    private javax.swing.JLabel lbpekerjaan;
    private javax.swing.JLabel lbprovinsi;
    private javax.swing.JLabel lbrtrw;
    private javax.swing.JLabel lbstatusperkawinan;
    private javax.swing.JLabel lbtempat;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtberlakuhingga;
    private javax.swing.JTextField txtkabupaten;
    private javax.swing.JTextField txtkecamatan;
    private javax.swing.JTextField txtkelurahan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtpekerjaan;
    private javax.swing.JTextField txtprovinsi;
    private javax.swing.JTextField txtrtrw;
    private javax.swing.JTextField txttempat;
    // End of variables declaration//GEN-END:variables

    private static class KTP {

        public KTP() {
        }
    }
}
